### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Bernardi23** [EYHN/vscode-vibrancy#20]
That's all we need now!

**Comment by incafox** [comment]
i like this ext on windows and mac, there is something that we can do to get this on linux?? what file/line should we modified for that purpose?/

**Comment by incafox** [comment]
https://github.com/ckissane/vscode

**Comment by ckissane** [comment]
@Bernardi23 contrary to popular belief this extension does work on linux, you just have to be using a transparency supporting compositor (like picom or kwin), and use the code-transparent aur package.

**Comment by milad2golnia** [comment]
> @Bernardi23 contrary to popular belief this extension does work on linux, you just have to be using a transparency supporting compositor (like picom or kwin), and use the code-transparent aur package.

I tried this solution but I wasn't successful to achieve the desired results and during that configuration I forced to downgrade the **nodejs** and unistall official VS Code which was annoying to me. To every one who is trying to make vscode transparent, I strongly recommend to use **Force Blur** Kwin Script, Using this script you didn't need to install another package(code-transparent).

I know this script is not the same but it's the best I can offer in current time. By the way, I hope someday this extension supports linux too.

**Comment by Shinigami92** [comment]
Hey @milad2golnia, thanks for your hint to **Force Blur**
But I cannot get it to work :thinking: 
Do you have any guide? Do I need to restart my system?

I also applied the folder and "(Uncheck -> Apply -> Check -> Apply)"

```bash
mkdir -p ~/.local/share/kservices5/
cp ~/.local/share/kwin/scripts/forceblur/metadata.desktop ~/.local/share/kservices5/forceblur.desktop
```

---

```yml
Operating System: Arch Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.10.25-1-lts
OS Type: 64-bit
Graphics Platform: X11
Processors: 28 × Intel® Core™ i9-10940X CPU @ 3.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: GeForce GTX 1080/PCIe/SSE2
```

![Screenshot_20210330_113052](https://user-images.githubusercontent.com/7195563/112967338-78313e80-914b-11eb-879a-de549a4dc8de.jpg)


![image](https://user-images.githubusercontent.com/7195563/112967171-40c29200-914b-11eb-8bcf-39f902ce9812.png)
